### ISSUE TITLE
Allowing to select/specify existing ECS service

### ISSUE THREAD

**Issue by jessie00chen** [docker/ecs-plugin#159]
We can specify existing VPC with x-aws-vpc in compose file, is there a way to specify existing service that is already provisioned?

**Comment by metcalfc** [comment]
The current `x-` parameters are here: https://docs.docker.com/engine/context/ecs-integration/#tuning-the-cloudformation-template.

```x-aws-vpc can be set as a top-level element in your Compose file to set the ARN of a VPC to use when deploying the Compose application.

x-aws-loadbalancer can be set as a top-level element in your Compose file to set the ARN of an existing LoadBalancer.

x-aws-securitygroup can be set inside a network definition in your Compose file to set the ARN of an existing SecurityGroup used to implement network connectivity between services.```

In `docker ecs setup` you can

```docker ecs setup
Enter context name: new
✔ sandbox.devtools.developer
Enter cluster name: myexistingcluster
```
Its not an arn but the simple name of the cluster as listed in the ECS console.

Does that answer you question? If so, we should add this to the docs. Thanks for the report.

**Comment by jessie00chen** [comment]
Thank you @metcalfc, that definitely clarifies it. What I was hoping for is not rely or create any stacks in CloudFormation at all. We are pretty deep with Terraform and would want to avoid 2 different systems managing AWS resources. Maybe what I was looking for is a flexible & easy way to point to either ECS services or local Docker instances via docker-compose or override with different developing or testing scenario, and maybe extra_hosts with compose could solve that problem for us. I am still evaluating the pros & cons.

**Comment by metcalfc** [comment]
Got it yeah in that case the closest you would be able to get is the lb, security group, vpc, and ecs cluster. We'd still use CF to generate the cloud map entries, cloud watch, ecs task definitions, etc. The stack is designed to be standalone and fully tagged. However, its all in AWS with CF stacks.

Since we recently moved the compose spec into the open we've been thinking about what compose will look like going forward and what that would mean for say bringing in cloud services. Its still super early days though. We'd be interested in hearing your use case over at our Roadmap repo: https://github.com/docker/roadmap/blob/master/CONTRIBUTING.MD

**Comment by ndeloof** [comment]
In terms of Compose model, what you describe is an external service that your application depends on, and will be managed independently: https://docs.docker.com/compose/compose-file/#external_links
I'm not sure how we can translate this into an ECS deployment, maybe register such an external service in CloudMap so dependent service can discover them by service name?

**Comment by jessie00chen** [comment]
@ndeloof If we can register external ecs service in cloudmap, do you think it could somehow be referenced by Compose when we do docker-compose up? My goal is to make sure developing locally is easier; not needing to introduce a local instance of nginx or hardcoded mapping runtime IP address in Compose. Have the ability to discover service locally either via CloudMap with Compose or just Compose itself would be ideal.

**Comment by jessie00chen** [comment]
@ndeloof look into https://docs.docker.com/compose/compose-file/#external_links a bit more, and seems like it's deprecated. With the recommended Compose network option, it seems like services can only communicates from the same docker host (laptop) within the same network, not sure if there is a way to establish a network locally(laptop) with ECS or CloudMap?

**Comment by ndeloof** [comment]
external_links is indeed deprecated by docker-compose docs, but still present in the compose specification (https://github.com/compose-spec/compose-spec) and so we could rely on it if relevant. Main reason for deprecation is that `link` is only implemented for containers running on the **same** engine, and as such can't be supported when targeting a distributed environment (docker swarm), but still the concept is relevant.

Main point would be to understand how we can make it easier to connect to external resources (hosted on ECS or other AWS services) so that you only need minimal changes in your application code / compose file to run both local during development and deploy to production platform.

**Comment by ndeloof** [comment]
closing for now as this would better be addressed first by discussing this topic on compose-spec
