### ISSUE TITLE
errors when running docker ecs compose up

### ISSUE THREAD

**Issue by rae89** [docker/ecs-plugin#193]
Hello, 

I am trying to run this docker-compose yaml file: https://github.com/apache/incubator-superset/blob/master/docker-compose.yml

And when I run : `docker ecs compose up` I get the following errors:

> WARN[0000] services.env_file: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.build: unsupported attribute
> WARN[0000] services.env_file: unsupported attribute
> ERRO[0000] service superset-worker doesn't define a Docker image to run: incompatible attribute
> WARN[0000] services.restart: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.build: unsupported attribute
> WARN[0000] services.env_file: unsupported attribute
> ERRO[0000] service superset-tests-worker doesn't define a Docker image to run: incompatible attribute
> WARN[0000] services.network_mode: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.restart: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.env_file: unsupported attribute
> WARN[0000] services.restart: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.build: unsupported attribute
> WARN[0000] services.env_file: unsupported attribute
> ERRO[0000] service superset doesn't define a Docker image to run: incompatible attribute
> WARN[0000] services.restart: unsupported attribute
> WARN[0000] services.volumes: unsupported attribute
> WARN[0000] services.build: unsupported attribute
> WARN[0000] services.env_file: unsupported attribute
> ERRO[0000] service superset-init doesn't define a Docker image to run: incompatible attribute
> WARN[0000] services.volumes: unsupported attribute

What would be required to support the docker-compose I have linked?

**Comment by chris-crone** [comment]
Hi @rae89,

The features we're currently missing are:
1. Building the image as part of `compose up`
2. Environment variables as a file
3. Volume support

For (1), the issue is that ECS does not handle images the same as your local Docker instance does. The workaround is to build the images, with something like `docker-compose build` and then push them to a registry. You will need to make sure that you add image names to each service as well. We have some ideas for how to improve the user experience here but no short term plans.

For (2), I think we can implement this quite easily. I've created a separate issue to track: https://github.com/docker/ecs-plugin/issues/196. The work around would be to set the [environment variables directly](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers).

For (3), we don't currently have a solution for this and need to think about it more. The challenge is with things like databases: locally you would like them to run as a container but in the cloud, you may want to use a hosted solution rather than maintaining a container and volume.

**Comment by rae89** [comment]
@chris-crone Thank you for the input.

**Comment by samuelcesc** [comment]
Hi @chris-crone , i'm using the docker ecs in beta. Is it possible to mount code on the image at the moment? Still getting the unsupported attribute warning for volumes.

**Comment by chris-crone** [comment]
Hi @samuelcesc! It [has been added](https://github.com/docker/compose-cli/pull/622) to the Compose CLI (the replacement for this plugin).

If you're using macOS or Windows, the next Docker Desktop release will include this. If you're using Linux, you can follow the install instructions and get the feature now: https://github.com/docker/compose-cli/blob/main/INSTALL.md
